<template>
    <div>
        <h1>Preferences</h1>
        <inertia-link
            method="post"
            href="/logout"
            as="button"
        >
            Logout
        </inertia-link>
    </div>
</template>